name: Deploy pages to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Inject password
        run: |
          sed -i 's/{{PASSWORD}}/${{ secrets.REVEAL_PW }}/g' docs/index.html
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/index.html
          git commit -m "Inject UI password"
          git push