name: Deploy pages to GitHub Pages

on:
  push:
    branches: [master]

permissions: 
  contents: write
  pages: write
  id-token: write


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Prepare token-injected site
        run: |
          mkdir build
          cp -r docs/* build/
          sed -i 's/{{PASSWORD}}/${{ secrets.REVEAL_PW }}/g' build/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4